version: "3"
services:
  selenium:
    image: selenium/hub
    ports:
      - "4444:4444"
  chromenode:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5555"
    depends_on:
      - selenium
#  demo_myapp:
#    build: ./
#    image: myapp:latest
#    volumes:
#      - ./:/myapp:rw
#    depends_on:
#      - selenium
#      - chromenode